### ISSUE TITLE
node tools/db version command not working

### ISSUE THREAD

**Issue by shravanjha** [kriasoft/nodejs-api-starter#40]
$ node tools/db.js version
Starting 'db:version'...
TypeError: Cannot read property 'hasTable' of undefined
    at Migrator._ensureTable (/usr/src/app/node_modules/knex/lib/migrate/index.js:248:22)
    at Migrator._listCompleted (/usr/src/app/node_modules/knex/lib/migrate/index.js:391:17)
    at Migrator.currentVersion (/usr/src/app/node_modules/knex/lib/migrate/index.js:177:17)
    at module.exports.task (/usr/src/app/tools/db.js:44:26)
    at Promise.resolve.then (/usr/src/app/tools/task.js:23:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Done in 2.61s.

**Comment by koistya** [comment]
https://github.com/tgriesser/knex/pull/2123

**Comment by koistya** [comment]
Fixed `yarn db` and `yarn psql` scripts.
