### ISSUE TITLE
docker-compose permission errors in Ubuntu 16.04

### ISSUE THREAD

**Issue by gpolyn** [kriasoft/nodejs-api-starter#43]
Setup:
- Ubuntu 16.04.02 (xenial)
- docker-compose version 1.11.2
- Docker version 17.06.0-ce

After `docker-compose up`, get positive results until api build stage:

```
api_1    | warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
api_1    | info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from instal
lation.
api_1    | [3/4] Linking dependencies...
api_1    | error Could not write file "/usr/src/app/yarn-error.log": "EACCES: permission denied, open '/usr/src/app
/yarn-error.log'"
api_1    | error An unexpected error occurred: "EACCES: permission denied, mkdir '/usr/src/app/node_modules/accepts
'".
api_1    | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
api_1    | module.js:487
api_1    |     throw err;
api_1    |     ^
api_1    | 
api_1    | Error: Cannot find module 'rimraf'
api_1    |     at Function.Module._resolveFilename (module.js:485:15)
api_1    |     at Function.Module._load (module.js:437:25)
api_1    |     at Module.require (module.js:513:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/usr/src/app/tools/build.js:13:16)
api_1    |     at Module._compile (module.js:569:30)
api_1    |     at Object.Module._extensions..js (module.js:580:10)
api_1    |     at Module.load (module.js:503:32)
api_1    |     at tryModuleLoad (module.js:466:12)
api_1    |     at Function.Module._load (module.js:458:3)
```
Thanks, G

**Comment by shadowbrush** [comment]
I think you need to run this as root on Ubuntu.

**Comment by gpolyn** [comment]
@shadowbrush I changed permissions on the directory and it worked.
