### ISSUE TITLE
App is not starting up 

### ISSUE THREAD

**Issue by ntaboada** [kriasoft/nodejs-api-starter#91]
I just clone the project and on the root of the project : 

1) Run npm install
2) docker-compose up

I am actually getting on my log -->

```
api_1    | Error: Cannot find module './server.js'
api_1    |     at Function.Module._resolveFilename (module.js:536:15)
api_1    |     at Function.Module._load (module.js:466:25)
api_1    |     at Module.require (module.js:579:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Socket.process.stdin.on.data ([eval]:1:68)
api_1    |     at emitOne (events.js:116:13)
api_1    |     at Socket.emit (events.js:211:7)
api_1    |     at addChunk (_stream_readable.js:263:12)
api_1    |     at readableAddChunk (_stream_readable.js:250:11)
api_1    |     at Socket.Readable.push (_stream_readable.js:208:10)
api_1    |     at Pipe.onread (net.js:594:20)

```

![captura de pantalla 2018-02-12 a las 1 16 50 2](https://user-images.githubusercontent.com/11520892/36083584-b5ac0396-0f92-11e8-81b9-b1a702219590.png)

Why its happening? Kind regards

**Comment by koistya** [comment]
@ntaboada can you please paste more log output (before `Cannot find module './server.js'` line)

**Comment by ntaboada** [comment]
This is the complete log:

```
owlblackbird$ docker-compose up
Starting app_db_1 ... 
Starting app_db_1
Starting app_redis_1 ... 
Starting app_db_1 ... done
Starting app_api_1 ... 
Starting app_api_1 ... done
Attaching to app_redis_1, app_db_1, app_api_1
redis_1  | 1:C 12 Feb 14:28:00.404 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 12 Feb 14:28:00.405 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
db_1     | LOG:  database system was interrupted; last known up at 2018-02-12 04:18:02 UTC
redis_1  | 1:C 12 Feb 14:28:00.405 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1     | LOG:  database system was not properly shut down; automatic recovery in progress
db_1     | LOG:  invalid record length at 0/15C4A80: wanted 24, got 0
redis_1  | 1:M 12 Feb 14:28:00.407 * Running mode=standalone, port=6379.
db_1     | LOG:  redo is not required
redis_1  | 1:M 12 Feb 14:28:00.407 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1  | 1:M 12 Feb 14:28:00.407 # Server initialized
db_1     | LOG:  MultiXact member wraparound protections are now enabled
redis_1  | 1:M 12 Feb 14:28:00.407 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db_1     | LOG:  database system is ready to accept connections
db_1     | LOG:  autovacuum launcher started
redis_1  | 1:M 12 Feb 14:28:00.407 * Ready to accept connections
api_1    | yarn install v1.3.2
api_1    | [1/4] Resolving packages...
api_1    | success Already up-to-date.
api_1    | Done in 0.58s.
api_1    | Starting 'run'...
api_1    | Starting 'db-migrate'...
api_1    | Finished 'db-migrate' after 175ms
api_1    | Starting 'build'...
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | src/schema/README.md -> build/schema/README.md
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | src/emails/welcome/html.hbs -> build/emails/welcome/html.js
api_1    | src/emails/welcome/subject.hbs -> build/emails/welcome/subject.js
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | EISDIR: illegal operation on a directory, read
api_1    | Finished 'build' after 292ms
api_1    | module.js:538
api_1    |     throw err;
api_1    |     ^
api_1    | 

```

**Comment by ntaboada** [comment]
Someone?

**Comment by shadowbrush** [comment]
This looks like an issue with the underlying setup: docker, npm. Have you tried to run a plain vanilla Node container, i.e. https://github.com/nodejs/docker-node ? You might get a better response at [gitter](https://gitter.im/kriasoft/nodejs-api-starter).

**Comment by andrewkslv** [comment]
@ntaboada you could try to remove all images, containers and try again. It's definitely an issue with underlying setup. I had the same at one time.

```
#!/bin/bash
# Delete all containers
docker rm $(docker ps -a -q)
# Delete all images
docker rmi $(docker images -q)
```

**Comment by reachdevelopers** [comment]
same here :(

**Comment by avallete** [comment]
The problem is related to the docker volumes permissions.

As a workaround, you can change the rights of the 'build' directory:

```
sudo chown username:docker ./build
```

Then, when you re-run `docker-compose up`, it should work without troubles.

**Comment by projectivemotion** [comment]
On my machine i believe i have my docker group ids mixed up so I ended up setting 777 on build/ .
